# Generated by Django 5.1.4 on 2025-06-02 13:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('benefits', models.JSONField(default=list, help_text='List of benefits')),
                ('requirements', models.JSONField(default=list, help_text='List of requirements')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('company_type', models.CharField(blank=True, choices=[('Startup', 'Startup'), ('SME', 'Small & Medium Enterprise'), ('Corporation', 'Corporation'), ('Non-profit', 'Non-profit'), ('Government', 'Government')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('Operating', 'Operating'), ('Stealth', 'Stealth Mode'), ('Pre-launch', 'Pre-launch'), ('Acquired', 'Acquired'), ('Closed', 'Closed')], default='Operating', max_length=50)),
                ('hq_country', models.CharField(max_length=100)),
                ('hq_city', models.CharField(max_length=100)),
                ('hq_address', models.TextField(blank=True, null=True)),
                ('employee_count', models.CharField(blank=True, choices=[('1', '1'), ('2-10', '2-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1000+', '1000+')], max_length=20, null=True)),
                ('total_funding_raised_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('contact_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('twitter_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('facebook_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('logo_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='pending', max_length=20)),
                ('submission_type', models.CharField(default='company_registration', max_length=50)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_companies', to=settings.AUTH_USER_MODEL)),
                ('industries', models.ManyToManyField(blank=True, to='api.industry')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['moderation_status'], name='api_company_moderat_4f617d_idx'), models.Index(fields=['company_type'], name='api_company_company_ab3de5_idx'), models.Index(fields=['hq_country'], name='api_company_hq_coun_68cf99_idx'), models.Index(fields=['status'], name='api_company_status_f30a20_idx')],
            },
        ),
    ]
