# Generated by Django 5.1.4 on 2025-06-02 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('Seed', 'Seed'), ('Pre-Seed', 'Pre-Seed'), ('Series A', 'Series A'), ('Series B', 'Series B'), ('Series C', 'Series C'), ('Series D+', 'Series D+'), ('Grant', 'Grant'), ('Debt', 'Debt Financing'), ('Equity Crowdfunding', 'Equity Crowdfunding'), ('ICO', 'Initial Coin Offering'), ('IPO', 'Initial Public Offering'), ('Angel', 'Angel Round'), ('Venture', 'Venture Round - Unspecified Series'), ('Undisclosed', 'Undisclosed'), ('Other', 'Other')], max_length=50)),
                ('announced_date', models.DateField()),
                ('money_raised_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pre_money_valuation_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('post_money_valuation_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('source_url', models.URLField(blank=True, help_text='URL of the announcement or source', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-announced_date', 'company__name'],
            },
        ),
        migrations.CreateModel(
            name='FundingRoundParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lead_investor', models.BooleanField(default=False)),
                ('amount_invested_usd', models.DecimalField(blank=True, decimal_places=2, help_text='If known for this specific investor in this round', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['funding_round__announced_date', 'investor__name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='person_profiles/')),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text="Admin moderation status. Only 'accepted' are public.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['full_name'],
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='NewsArticle',
        ),
        migrations.DeleteModel(
            name='PageContent',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='investor',
            options={'ordering': ['name'], 'verbose_name_plural': 'Investors'},
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='api_company_moderat_4f617d_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='api_company_company_ab3de5_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='api_company_hq_coun_68cf99_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='api_company_status_f30a20_idx',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='employee_count',
        ),
        migrations.RemoveField(
            model_name='company',
            name='hq_address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='company',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='company',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='submission_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='company',
            name='view_count',
        ),
        migrations.AddField(
            model_name='company',
            name='angellist_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='crunchbase_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_count_range',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1001-5000', '1001-5000 employees'), ('5000+', '5000+ employees')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_funding_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_funding_stage',
            field=models.CharField(blank=True, help_text='e.g., Seed, Series A, Grant, IPO', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo image file.', null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text="Admin moderation status. Only 'accepted' are public.", max_length=20),
        ),
        migrations.AddField(
            model_name='industry',
            name='parent_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_industries', to='api.industry'),
        ),
        migrations.AddField(
            model_name='industry',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='funding_stages_focus',
            field=models.CharField(blank=True, help_text='Comma-separated list of stages, e.g., Seed, Series A, Growth', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='hq_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='hq_country',
            field=models.CharField(blank=True, default='Ethiopia', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='industries_focus',
            field=models.ManyToManyField(blank=True, related_name='focused_investors', to='api.industry'),
        ),
        migrations.AddField(
            model_name='investor',
            name='investor_type',
            field=models.CharField(blank=True, choices=[('VC', 'Venture Capital'), ('Angel', 'Angel Investor'), ('PE', 'Private Equity'), ('Corporate', 'Corporate Venture Arm'), ('Accelerator', 'Accelerator/Incubator'), ('Government', 'Government Fund'), ('FamilyOffice', 'Family Office'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='investor_logos/'),
        ),
        migrations.AddField(
            model_name='investor',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text="Admin moderation status. Only 'accepted' are public.", max_length=20),
        ),
        migrations.AddField(
            model_name='investor',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('Private', 'Private Company'), ('Public', 'Public Company'), ('Non-profit', 'Non-profit'), ('Government', 'Government Entity'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='hq_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='hq_country',
            field=models.CharField(blank=True, default='Ethiopia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='companies', to='api.industry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text="Admin moderation status. Only 'accepted' are public.", max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_description',
            field=models.CharField(blank=True, help_text='A brief tagline or summary.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Leave blank to auto-generate from name.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, choices=[('Operating', 'Operating'), ('Acquired', 'Acquired'), ('Closed', 'Closed'), ('IPO', 'IPO')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_funding_raised_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='In USD', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='fundinground',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rounds', to='api.company'),
        ),
        migrations.AddField(
            model_name='fundingroundparticipation',
            name='funding_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fundinground'),
        ),
        migrations.AddField(
            model_name='fundingroundparticipation',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.investor'),
        ),
        migrations.AddField(
            model_name='fundinground',
            name='investors',
            field=models.ManyToManyField(related_name='investments_made', through='api.FundingRoundParticipation', to='api.investor'),
        ),
        migrations.AddField(
            model_name='company',
            name='founders',
            field=models.ManyToManyField(blank=True, help_text='People who founded this company.', related_name='founded_companies', to='api.person'),
        ),
        migrations.AddField(
            model_name='company',
            name='key_people',
            field=models.ManyToManyField(blank=True, help_text='Current key personnel.', related_name='current_companies', to='api.person'),
        ),
        migrations.AlterUniqueTogether(
            name='fundingroundparticipation',
            unique_together={('funding_round', 'investor')},
        ),
    ]
