# Generated by Django 5.1.4 on 2025-06-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fundinground_fundingroundparticipation_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('report', 'Report'), ('guide', 'Guide'), ('resource', 'Resource'), ('news', 'News'), ('other', 'Other')], default='article', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='curated_content/')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='curated_content_files/')),
                ('content', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text="Admin moderation status. Only 'accepted' are public.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industries', models.ManyToManyField(blank=True, related_name='curated_content', to='api.industry')),
                ('related_companies', models.ManyToManyField(blank=True, related_name='curated_content', to='api.company')),
            ],
            options={
                'verbose_name_plural': 'Curated Content',
                'ordering': ['-featured', 'order', '-published_date'],
            },
        ),
    ]
