# Generated by Django 5.1.4 on 2025-06-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_curatedcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcosystemBuilderRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('full_name_and_position', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('Innovation hub or incubator', 'Innovation hub or incubator'), ('University or TVET', 'University or TVET'), ('Government body', 'Government body'), ('NGO / CSO', 'NGO / CSO'), ('Private company', 'Private company'), ('Investor', 'Investor'), ('Donor or international agency', 'Donor or international agency'), ('Other', 'Other')], max_length=64)),
                ('support_services', models.JSONField(default=list)),
                ('operating_duration', models.CharField(max_length=100)),
                ('notable_programs', models.TextField()),
                ('collaboration', models.TextField()),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Ecosystem Builder Registration',
                'verbose_name_plural': 'Ecosystem Builder Registrations',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
