# Generated by Django 5.1.4 on 2025-06-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_company_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, choices=[('Operating', 'Operating'), ('Stealth', 'Stealth Mode'), ('Pre-launch', 'Pre-launch'), ('Acquired', 'Acquired'), ('Closed', 'Closed')], max_length=50, null=True),
        ),
    ]
