# Generated by Django 5.1.4 on 2025-06-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_company_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_type', models.CharField(choices=[('startup', 'Startup'), ('scaleup', 'Scaleup'), ('vc', 'Venture Capital'), ('angel', 'Angel Investor'), ('accelerator', 'Accelerator'), ('incubator', 'Incubator'), ('hub', 'Innovation Hub'), ('university', 'University'), ('government', 'Government Body'), ('corporate', 'Corporate'), ('ngo', 'NGO/Non-Profit'), ('service_provider', 'Service Provider')], max_length=20)),
                ('organization_name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('employee_count', models.CharField(blank=True, max_length=20, null=True)),
                ('headquarters', models.CharField(max_length=100)),
                ('country', models.CharField(default='Ethiopia', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(max_length=100)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('sectors', models.JSONField(blank=True, default=list)),
                ('funding_stage', models.CharField(blank=True, choices=[('pre_seed', 'Pre-seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c_plus', 'Series C+'), ('growth', 'Growth'), ('ipo', 'IPO'), ('not_applicable', 'Not applicable')], max_length=20, null=True)),
                ('total_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('key_achievements', models.TextField(blank=True, null=True)),
                ('subscribe_newsletter', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Needs More Information')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Organization Registration',
                'verbose_name_plural': 'Organization Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
